component_depth: 4
languages:
- java
- name: java
  production:
    exclude:
      - .*/perf/java/rx/.*.java
      - .*/test/java/rx/.*.java
      - .*/gradle/.*.java
  test:
    include:
      - .*/test/java/rx/.*.java
